language: node_js

node_js:
  - 8
before_install:
  - npm i

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm install -g semantic-release@^15
          - semantic-release